/**
 * Catalogue des ressources et services Greffio (prix indicatifs, modifiables ici).
 */

export const RESOURCE_KIND_LABELS = {
  service: 'Service',
  document: 'Document officiel',
  guide: 'Guide',
  pack: 'Pack',
  tool: 'Outil rapide',
};

export const CATEGORY_LABELS = {
  official_document: 'Document officiel',
  certified_copy: 'Copie certifiée',
  simple_service: 'Service rapide',
  pack: 'Pack Greffio',
  guide: 'Guide',
  tool: 'Outil',
};

const item = (entry) => ({
  available: true,
  processingMode: 'guided',
  requiresCompany: true,
  requiresSiren: true,
  actionLabel: 'Commander',
  source: 'Greffio',
  searchTerms: [],
  ...entry,
  searchTerms: [
    ...(entry.searchTerms || []),
    entry.title,
    entry.description,
    CATEGORY_LABELS[entry.category],
    RESOURCE_KIND_LABELS[entry.kind],
  ].filter(Boolean),
});

export const QUICK_ACCESS = [
  { id: 'qa-guides', guideId: 'guide-kbis', label: 'Guides gratuits', icon: 'book' },
  { id: 'qa-verify', serviceId: 'company-verify', label: 'Vérifier une entreprise', icon: 'search' },
  { id: 'qa-siren', toolId: 'tool-siren', label: 'Vérifier un SIREN', icon: 'search' },
  { id: 'qa-kbis', serviceId: 'kbis-extract', label: 'Obtenir un Kbis', icon: 'file-badge' },
  { id: 'qa-certified', serviceId: 'certified-statutes', label: 'Copie certifiée', icon: 'stamp' },
  { id: 'qa-dossier-docs', toolId: 'tool-dossier-docs', label: 'Documents de mon dossier', icon: 'folder', requiresAuth: true },
];

export const isResourceFree = (item) => !item?.priceTtc || Number(item.priceTtc) <= 0;

/** Tri psychologique : gratuits d’abord */
export const sortFreeFirst = (items) => [...items].sort((a, b) => {
  const aFree = isResourceFree(a);
  const bFree = isResourceFree(b);
  if (aFree !== bFree) return aFree ? -1 : 1;
  return 0;
});

export const POPULAR_SEARCHES = [
  'Extrait Kbis',
  'Copie certifiée de statuts',
  'Bénéficiaires effectifs',
  'Transfert de siège',
  'Certificat de non-opposition',
];

export const OFFICIAL_DOCUMENTS = [
  item({
    id: 'kbis-extract',
    kind: 'document',
    category: 'official_document',
    title: 'Extrait Kbis',
    description: 'Extrait d’immatriculation au registre du commerce et des sociétés.',
    priceTtc: 4.9,
    estimatedDelay: '24 à 48 h ouvrées',
    actionLabel: 'Commander',
    processingMode: 'guided',
    searchTerms: ['kbis', 'extrait', 'rcs', 'immatriculation'],
  }),
  item({
    id: 'rne-extract',
    kind: 'document',
    category: 'official_document',
    title: 'Extrait RNE / immatriculation',
    description: 'Informations d’immatriculation issues du registre national des entreprises.',
    priceTtc: 4.9,
    estimatedDelay: '24 à 48 h ouvrées',
    searchTerms: ['rne', 'registre national', 'immatriculation'],
  }),
  item({
    id: 'debt-status',
    kind: 'document',
    category: 'official_document',
    title: 'État d’endettement',
    description: 'Document relatif à la situation d’endettement de la société lorsque disponible.',
    priceTtc: 9.9,
    estimatedDelay: '2 à 5 jours ouvrés',
    searchTerms: ['endettement', 'dettes'],
  }),
  item({
    id: 'non-opposition-cert',
    kind: 'document',
    category: 'official_document',
    title: 'Certificat de non-opposition',
    description: 'Attestation utile dans certaines opérations sur le capital ou les apports.',
    priceTtc: 12.9,
    estimatedDelay: '3 à 7 jours ouvrés',
    searchTerms: ['non opposition', 'certificat', 'apport'],
  }),
  item({
    id: 'rcs-history',
    kind: 'document',
    category: 'official_document',
    title: 'Historique des modifications RCS',
    description: 'Synthèse des modifications déposées au greffe compétent.',
    priceTtc: 14.9,
    estimatedDelay: '3 à 7 jours ouvrés',
    searchTerms: ['historique', 'modifications', 'rcs', 'greffe'],
  }),
  item({
    id: 'collective-procedure-info',
    kind: 'document',
    category: 'official_document',
    title: 'Informations de procédures collectives',
    description: 'Vérification des procédures collectives connues lorsque la source le permet.',
    priceTtc: 9.9,
    estimatedDelay: '24 à 72 h ouvrées',
    searchTerms: ['procédure collective', 'liquidation', 'redressement'],
  }),
  item({
    id: 'ubo-info',
    kind: 'document',
    category: 'official_document',
    title: 'Bénéficiaires effectifs',
    description: 'Récupération ou préparation documentaire des bénéficiaires effectifs selon droits d’accès.',
    priceTtc: 12.9,
    estimatedDelay: '2 à 5 jours ouvrés',
    available: true,
    processingMode: 'guided',
    searchTerms: ['bénéficiaires effectifs', 'rbe', 'ubo'],
  }),
];

export const CERTIFIED_COPIES = [
  item({
    id: 'certified-statutes',
    kind: 'document',
    category: 'certified_copy',
    title: 'Copie certifiée des statuts',
    description: 'Reproduction certifiée conforme des statuts déposés.',
    priceTtc: 1.49,
    promotionalPriceTtc: 1.49,
    originalPriceTtc: 14.9,
    estimatedDelay: '3 à 7 jours ouvrés',
    searchTerms: ['statuts', 'copie certifiée', 'actes'],
  }),
  item({
    id: 'certified-acts',
    kind: 'document',
    category: 'certified_copy',
    title: 'Copie certifiée d’actes',
    description: 'Actes et pièces déposées au registre, sur demande précise.',
    priceTtc: 1.49,
    promotionalPriceTtc: 1.49,
    originalPriceTtc: 14.9,
    estimatedDelay: '3 à 7 jours ouvrés',
    searchTerms: ['actes', 'copie', 'greffe'],
  }),
  item({
    id: 'certified-accounts',
    kind: 'document',
    category: 'certified_copy',
    title: 'Copie certifiée des comptes annuels',
    description: 'Comptes annuels déposés, selon disponibilité au greffe.',
    priceTtc: 16.9,
    estimatedDelay: '5 à 10 jours ouvrés',
    searchTerms: ['comptes annuels', 'bilan'],
  }),
  item({
    id: 'certified-amendment',
    kind: 'document',
    category: 'certified_copy',
    title: 'Copie d’un dépôt modificatif',
    description: 'Modification statutaire ou déclarative déjà publiée.',
    priceTtc: 12.9,
    estimatedDelay: '3 à 7 jours ouvrés',
    searchTerms: ['modification', 'dépôt', 'pv'],
  }),
  item({
    id: 'certified-director',
    kind: 'document',
    category: 'certified_copy',
    title: 'Acte de nomination ou changement de dirigeant',
    description: 'Pièce relative à la gouvernance déposée au registre.',
    priceTtc: 12.9,
    estimatedDelay: '3 à 7 jours ouvrés',
    searchTerms: ['dirigeant', 'président', 'nomination'],
  }),
  item({
    id: 'certified-pv',
    kind: 'document',
    category: 'certified_copy',
    title: 'Copie d’un procès-verbal déposé',
    description: 'PV d’assemblée ou de décision collective déposé.',
    priceTtc: 12.9,
    estimatedDelay: '3 à 7 jours ouvrés',
    searchTerms: ['procès-verbal', 'pv', 'ago', 'age'],
  }),
];

export const SIMPLE_SERVICES = [
  item({
    id: 'company-verify',
    kind: 'service',
    category: 'simple_service',
    title: 'Vérification d’existence d’une société',
    description: 'Contrôle rapide de l’identité légale et du statut administratif.',
    priceTtc: 0,
    estimatedDelay: 'Immédiat',
    requiresSiren: true,
    requiresCompany: false,
    actionLabel: 'Vérifier',
    processingMode: 'available',
    available: true,
    searchTerms: ['vérifier', 'existence', 'siren'],
  }),
  item({
    id: 'company-search',
    kind: 'service',
    category: 'simple_service',
    title: 'Recherche d’entreprise',
    description: 'Recherche par dénomination ou SIREN via les sources publiques.',
    priceTtc: 0,
    estimatedDelay: 'Immédiat',
    actionLabel: 'Rechercher',
    processingMode: 'available',
    available: true,
    searchTerms: ['recherche entreprise', 'annuaire'],
  }),
  item({
    id: 'admin-certificate',
    kind: 'service',
    category: 'simple_service',
    title: 'Demande de certificat administratif',
    description: 'Commande guidée d’un certificat selon la formalité visée.',
    priceTtc: 12.9,
    estimatedDelay: '3 à 7 jours ouvrés',
    searchTerms: ['certificat administratif'],
  }),
  item({
    id: 'documentary-pack',
    kind: 'service',
    category: 'simple_service',
    title: 'Constitution d’un dossier documentaire',
    description: 'Assemblage des pièces disponibles pour une formalité ou un contrôle.',
    priceTtc: 24.9,
    estimatedDelay: '2 à 5 jours ouvrés',
    searchTerms: ['dossier documentaire', 'pack documents'],
  }),
  item({
    id: 'download-pack',
    kind: 'service',
    category: 'simple_service',
    title: 'Téléchargement d’un pack disponible',
    description: 'Export des documents déjà générés ou validés dans Greffio.',
    priceTtc: 0,
    estimatedDelay: 'Immédiat',
    actionLabel: 'Voir mon espace',
    processingMode: 'available',
    requiresCompany: false,
    requiresSiren: false,
    available: true,
    searchTerms: ['télécharger', 'export'],
  }),
];

export const PACKS = [
  item({
    id: 'pack-creation',
    kind: 'pack',
    category: 'pack',
    title: 'Pack Création',
    description: 'Documents types, checklist et suivi pour une création de société.',
    priceTtc: 24.9,
    estimatedDelay: 'Sous 48 h ouvrées',
    searchTerms: ['création', 'pack', 'immatriculation'],
  }),
  item({
    id: 'pack-modification',
    kind: 'pack',
    category: 'pack',
    title: 'Pack Modification',
    description: 'Pièces et modèles pour une modification statutaire courante.',
    priceTtc: 24.9,
    estimatedDelay: 'Sous 48 h ouvrées',
    searchTerms: ['modification société', 'pack'],
  }),
  item({
    id: 'pack-director',
    kind: 'pack',
    category: 'pack',
    title: 'Pack Dirigeant',
    description: 'Nomination, révocation, mandats et déclarations associées.',
    priceTtc: 19.9,
    estimatedDelay: 'Sous 48 h ouvrées',
    searchTerms: ['dirigeant', 'président', 'pack'],
  }),
  item({
    id: 'pack-establishment',
    kind: 'pack',
    category: 'pack',
    title: 'Pack Établissement',
    description: 'Ouverture, transfert ou fermeture d’établissement.',
    priceTtc: 19.9,
    estimatedDelay: 'Sous 48 h ouvrées',
    searchTerms: ['établissement', 'secondaire'],
  }),
  item({
    id: 'pack-compliance',
    kind: 'pack',
    category: 'pack',
    title: 'Pack Conformité administrative',
    description: 'Suivi documentaire, registres et obligations récurrentes.',
    priceTtc: 39.9,
    estimatedDelay: 'Sous 72 h ouvrées',
    searchTerms: ['conformité', 'obligations', 'pack'],
  }),
  item({
    id: 'pack-dd-light',
    kind: 'pack',
    category: 'pack',
    title: 'Pack investisseur / due diligence léger',
    description: 'Synthèse documentaire pour une reprise ou un contrôle rapide.',
    priceTtc: 49.9,
    estimatedDelay: '3 à 7 jours ouvrés',
    searchTerms: ['due diligence', 'investisseur'],
  }),
];

export const GUIDES = [
  item({
    id: 'guide-kbis',
    kind: 'guide',
    category: 'guide',
    title: 'Comprendre le Kbis',
    description: 'À quoi sert l’extrait Kbis et quand le demander.',
    priceTtc: 0,
    estimatedDelay: 'Lecture immédiate',
    requiresCompany: false,
    requiresSiren: false,
    actionLabel: 'Voir le guide',
    processingMode: 'available',
    available: true,
    searchTerms: ['kbis', 'comprendre'],
  }),
  item({
    id: 'guide-rne',
    kind: 'guide',
    category: 'guide',
    title: 'Comprendre le RNE',
    description: 'Registre national des entreprises : rôle et usages.',
    priceTtc: 0,
    estimatedDelay: 'Lecture immédiate',
    requiresCompany: false,
    requiresSiren: false,
    actionLabel: 'Voir le guide',
    processingMode: 'available',
    available: true,
    searchTerms: ['rne', 'registre'],
  }),
  item({
    id: 'guide-creation-docs',
    kind: 'guide',
    category: 'guide',
    title: 'Quels documents pour créer une société ?',
    description: 'Liste des pièces habituelles selon la forme juridique.',
    priceTtc: 0,
    estimatedDelay: 'Lecture immédiate',
    actionLabel: 'Voir le guide',
    processingMode: 'available',
    available: true,
    searchTerms: ['documents création', 'pièces'],
  }),
  item({
    id: 'guide-director-change',
    kind: 'guide',
    category: 'guide',
    title: 'Comment modifier un dirigeant ?',
    description: 'Étapes, décisions, dépôts et délais usuels.',
    priceTtc: 0,
    estimatedDelay: 'Lecture immédiate',
    actionLabel: 'Voir le guide',
    processingMode: 'available',
    available: true,
    searchTerms: ['dirigeant', 'changement', 'nomination'],
  }),
  item({
    id: 'guide-collective',
    kind: 'guide',
    category: 'guide',
    title: 'Que signifie une procédure collective ?',
    description: 'Redressement, liquidation et impacts pour les tiers.',
    priceTtc: 0,
    estimatedDelay: 'Lecture immédiate',
    actionLabel: 'Voir le guide',
    processingMode: 'available',
    available: true,
    searchTerms: ['procédure collective'],
  }),
  item({
    id: 'guide-kbis-rne-sirene',
    kind: 'guide',
    category: 'guide',
    title: 'Kbis, RNE et avis Sirene',
    description: 'Différences entre les documents et leurs usages.',
    priceTtc: 0,
    estimatedDelay: 'Lecture immédiate',
    actionLabel: 'Voir le guide',
    processingMode: 'available',
    available: true,
    searchTerms: ['sirene', 'différence', 'kbis'],
  }),
  item({
    id: 'guide-sasu',
    kind: 'guide',
    category: 'guide',
    title: 'Guide création SASU',
    description: 'Parcours, documents et points de vigilance.',
    priceTtc: 0,
    actionLabel: 'Voir le guide',
    processingMode: 'available',
    available: true,
    searchTerms: ['sasu', 'création'],
  }),
  item({
    id: 'guide-sas',
    kind: 'guide',
    category: 'guide',
    title: 'Guide création SAS',
    description: 'Associés, gouvernance, capital et dépôt.',
    priceTtc: 0,
    actionLabel: 'Voir le guide',
    processingMode: 'available',
    available: true,
    searchTerms: ['sas'],
  }),
  item({
    id: 'guide-sarl',
    kind: 'guide',
    category: 'guide',
    title: 'Guide création SARL',
    description: 'Parts sociales, gérant et formalités.',
    priceTtc: 0,
    actionLabel: 'Voir le guide',
    processingMode: 'available',
    available: true,
    searchTerms: ['sarl'],
  }),
  item({
    id: 'guide-seat-transfer',
    kind: 'guide',
    category: 'guide',
    title: 'Guide transfert de siège',
    description: 'Décision, justificatif et publicité.',
    priceTtc: 0,
    actionLabel: 'Voir le guide',
    processingMode: 'available',
    available: true,
    searchTerms: ['transfert siège', 'déménagement'],
  }),
  item({
    id: 'guide-dissolution',
    kind: 'guide',
    category: 'guide',
    title: 'Guide dissolution',
    description: 'Clôture, liquidation et radiation.',
    priceTtc: 0,
    actionLabel: 'Voir le guide',
    processingMode: 'available',
    available: true,
    searchTerms: ['dissolution', 'fermeture société'],
  }),
  item({
    id: 'guide-filing',
    kind: 'guide',
    category: 'guide',
    title: 'Guide dépôt au greffe',
    description: 'Préparer un dépôt clair et complet.',
    priceTtc: 0,
    actionLabel: 'Voir le guide',
    processingMode: 'available',
    available: true,
    searchTerms: ['dépôt greffe', 'formalité'],
  }),
];

export const QUICK_TOOLS = [
  item({
    id: 'tool-siren',
    kind: 'tool',
    category: 'tool',
    title: 'Vérifier un SIREN',
    description: 'Contrôle immédiat via l’annuaire des entreprises.',
    priceTtc: 0,
    actionLabel: 'Lancer',
    processingMode: 'available',
    available: true,
    toolRoute: 'siren',
    requiresCompany: false,
    searchTerms: ['siren', 'siret'],
  }),
  item({
    id: 'tool-company-search',
    kind: 'tool',
    category: 'tool',
    title: 'Rechercher une entreprise',
    description: 'Trouver une société par nom ou identifiant.',
    priceTtc: 0,
    actionLabel: 'Rechercher',
    processingMode: 'available',
    available: true,
    toolRoute: 'search',
    requiresCompany: false,
  }),
  item({
    id: 'tool-seat',
    kind: 'tool',
    category: 'tool',
    title: 'Vérifier une adresse de siège',
    description: 'Préparer le justificatif et les mentions utiles.',
    priceTtc: 0,
    actionLabel: 'Préparer',
    processingMode: 'available',
    available: true,
    toolRoute: '/guide',
    requiresCompany: false,
  }),
  item({
    id: 'tool-estimate-docs',
    kind: 'tool',
    category: 'tool',
    title: 'Estimer les documents nécessaires',
    description: 'Checklist selon la formalité envisagée.',
    priceTtc: 0,
    actionLabel: 'Simuler',
    processingMode: 'available',
    available: true,
    toolRoute: '/simulateur',
    requiresCompany: false,
  }),
  item({
    id: 'tool-prepare-formality',
    kind: 'tool',
    category: 'tool',
    title: 'Préparer un dossier de formalité',
    description: 'Démarrer un parcours guidé Greffio.',
    priceTtc: 0,
    actionLabel: 'Démarrer',
    processingMode: 'available',
    available: true,
    toolRoute: '/simulateur',
    requiresCompany: false,
  }),
  item({
    id: 'tool-dossier-docs',
    kind: 'tool',
    category: 'tool',
    title: 'Voir les documents manquants',
    description: 'Accéder à la checklist de votre dossier actif.',
    priceTtc: 0,
    actionLabel: 'Mon espace',
    processingMode: 'available',
    available: true,
    toolRoute: '/documents',
    requiresCompany: false,
    requiresAuth: true,
  }),
];

export const FREE_RESOURCE_HIGHLIGHTS = sortFreeFirst([
  ...SIMPLE_SERVICES.filter(isResourceFree),
  ...QUICK_TOOLS,
  ...GUIDES,
]).slice(0, 8);

export const LEGACY_ESTIMATORS = [
  { id: 'legacy-form', title: 'Simulateur de forme juridique', text: 'Comparer SAS, SARL, SA, EI, SCI et autres formes.', to: '/simulateur?type=statuts' },
  { id: 'legacy-charges', title: 'Calcul de charges sociales', text: 'Estimation dirigeant salarié ou TNS.', to: '/simulateur?type=charges' },
  { id: 'legacy-cost', title: 'Estimation du coût de création', text: 'Accompagnement, annonce légale, greffe et frais tiers.', to: '/paiement' },
  { id: 'legacy-acre', title: 'Pré-vérification ACRE', text: 'Critères et impacts de l’aide à la création.', to: '/simulateur?type=acre' },
  { id: 'legacy-name', title: 'Vérification de nom', text: 'Premier niveau de contrôle du nom envisagé.', to: '/simulateur?type=nom' },
  { id: 'legacy-legal', title: 'Mentions légales', text: 'Base CGU, CGV et politique de confidentialité.', to: '/simulateur?type=mentions' },
];

export const getAllCatalogItems = () => [
  ...OFFICIAL_DOCUMENTS,
  ...CERTIFIED_COPIES,
  ...SIMPLE_SERVICES,
  ...PACKS,
  ...GUIDES,
  ...QUICK_TOOLS,
];

export const getCatalogItemById = (id) => getAllCatalogItems().find((entry) => entry.id === id) || null;

export const formatResourcePrice = (priceTtc) => {
  if (!priceTtc || Number(priceTtc) <= 0) return 'Gratuit';
  return `${Number(priceTtc).toFixed(2).replace('.', ',')} € TTC`;
};

export const getProcessingLabel = (item) => {
  if (!item?.available) return 'Disponible prochainement';
  if (item.processingMode === 'guided') return 'Traitement par l’équipe Greffio';
  if (item.processingMode === 'coming_soon') return 'Disponible prochainement';
  return 'Commande guidée';
};

/** Paiement en ligne – confirmé aussi via GET /api/resources/config */
export const RESOURCE_PAYMENT_ENABLED = true;

export const isResourceOrderable = (item) => (
  Boolean(item?.available)
  && item.kind !== 'guide'
  && item.kind !== 'tool'
  && Number(item?.priceTtc) > 0
  && item.processingMode !== 'coming_soon'
);
