const DOSSIER_STATUSES = Object.freeze({
  DRAFT: 'draft',
  CONTACT_STARTED: 'contact_started',
  CONTACT_COMPLETED: 'contact_completed',
  LEGAL_FORM_SELECTED: 'legal_form_selected',
  QUESTIONNAIRE_IN_PROGRESS: 'questionnaire_in_progress',
  QUESTIONNAIRE_COMPLETED: 'questionnaire_completed',
  DOCUMENTS_REQUESTED: 'documents_requested',
  DOCUMENTS_UPLOADED: 'documents_uploaded',
  DOCUMENTS_UNDER_REVIEW: 'documents_under_review',
  DOCUMENTS_MISSING_OR_INVALID: 'documents_missing_or_invalid',
  MANDATE_REQUIRED: 'mandate_required',
  MANDATE_SIGNED: 'mandate_signed',
  STATUTES_GENERATED: 'statutes_generated',
  STATUTES_UNDER_REVIEW: 'statutes_under_review',
  STATUTES_SIGNED: 'statutes_signed',
  PAYMENT_PENDING: 'payment_pending',
  PAYMENT_CONFIRMED: 'payment_confirmed',
  DOSSIER_PREPARATION: 'dossier_preparation',
  CLIENT_VALIDATION_REQUIRED: 'client_validation_required',
  CLIENT_VALIDATED: 'client_validated',
  READY_FOR_FILING: 'ready_for_filing',
  FILED_TO_GUICHET_UNIQUE: 'filed_to_guichet_unique',
  UNDER_ADMINISTRATION_REVIEW: 'under_administration_review',
  REGULARIZATION_REQUESTED: 'regularization_requested',
  REGULARIZATION_SUBMITTED: 'regularization_submitted',
  ACCEPTED: 'accepted',
  OFFICIAL_DOCUMENTS_AVAILABLE: 'official_documents_available',
  COMPLETED: 'completed',
  REJECTED: 'rejected',
  ABANDONED: 'abandoned',
  CANCELLED_BY_CLIENT: 'cancelled_by_client',
  PAYMENT_FAILED: 'payment_failed',
  MANUAL_REVIEW_REQUIRED: 'manual_review_required',
  REFUNDED: 'refunded',

  // Backward compatibility aliases
  QUESTIONNAIRE_STARTED: 'questionnaire_in_progress',
  QUOTE_GENERATED: 'questionnaire_completed',
  PAID: 'payment_confirmed',
  DOCUMENTS_GENERATING: 'dossier_preparation',
  DOCUMENTS_READY: 'client_validation_required',
  FORMALIST_REVIEW_PENDING: 'documents_under_review',
  FORMALIST_REVIEWED: 'documents_uploaded',
  SIGNATURE_PENDING: 'mandate_required',
  SIGNED: 'mandate_signed',
  LEGAL_NOTICE_PENDING: 'ready_for_filing',
  LEGAL_NOTICE_PUBLISHED: 'filed_to_guichet_unique',
  INPI_READY: 'ready_for_filing',
  INPI_SUBMITTED: 'filed_to_guichet_unique',
  INPI_UNDER_REVIEW: 'under_administration_review',
  REGULARIZATION_ANSWERED: 'regularization_submitted',
  KBIS_RECEIVED: 'official_documents_available',
  CLOSED: 'completed',
  CANCELLED: 'cancelled_by_client',
});

const ALLOWED_TRANSITIONS = Object.freeze({
  [DOSSIER_STATUSES.DRAFT]: [
    DOSSIER_STATUSES.CONTACT_STARTED,
    DOSSIER_STATUSES.CANCELLED_BY_CLIENT,
    DOSSIER_STATUSES.ABANDONED,
  ],
  [DOSSIER_STATUSES.CONTACT_STARTED]: [
    DOSSIER_STATUSES.CONTACT_COMPLETED,
    DOSSIER_STATUSES.ABANDONED,
  ],
  [DOSSIER_STATUSES.CONTACT_COMPLETED]: [
    DOSSIER_STATUSES.LEGAL_FORM_SELECTED,
    DOSSIER_STATUSES.ABANDONED,
  ],
  [DOSSIER_STATUSES.LEGAL_FORM_SELECTED]: [
    DOSSIER_STATUSES.QUESTIONNAIRE_IN_PROGRESS,
  ],
  [DOSSIER_STATUSES.QUESTIONNAIRE_IN_PROGRESS]: [
    DOSSIER_STATUSES.QUESTIONNAIRE_COMPLETED,
    DOSSIER_STATUSES.ABANDONED,
  ],
  [DOSSIER_STATUSES.QUESTIONNAIRE_COMPLETED]: [
    DOSSIER_STATUSES.DOCUMENTS_REQUESTED,
    DOSSIER_STATUSES.MANUAL_REVIEW_REQUIRED,
  ],
  [DOSSIER_STATUSES.DOCUMENTS_REQUESTED]: [
    DOSSIER_STATUSES.DOCUMENTS_UPLOADED,
    DOSSIER_STATUSES.DOCUMENTS_MISSING_OR_INVALID,
  ],
  [DOSSIER_STATUSES.DOCUMENTS_MISSING_OR_INVALID]: [
    DOSSIER_STATUSES.DOCUMENTS_UPLOADED,
    DOSSIER_STATUSES.ABANDONED,
  ],
  [DOSSIER_STATUSES.DOCUMENTS_UPLOADED]: [
    DOSSIER_STATUSES.DOCUMENTS_UNDER_REVIEW,
  ],
  [DOSSIER_STATUSES.DOCUMENTS_UNDER_REVIEW]: [
    DOSSIER_STATUSES.MANDATE_REQUIRED,
    DOSSIER_STATUSES.DOCUMENTS_MISSING_OR_INVALID,
  ],
  [DOSSIER_STATUSES.MANDATE_REQUIRED]: [
    DOSSIER_STATUSES.MANDATE_SIGNED,
  ],
  [DOSSIER_STATUSES.MANDATE_SIGNED]: [
    DOSSIER_STATUSES.STATUTES_GENERATED,
  ],
  [DOSSIER_STATUSES.STATUTES_GENERATED]: [
    DOSSIER_STATUSES.STATUTES_UNDER_REVIEW,
  ],
  [DOSSIER_STATUSES.STATUTES_UNDER_REVIEW]: [
    DOSSIER_STATUSES.STATUTES_SIGNED,
    DOSSIER_STATUSES.DOCUMENTS_MISSING_OR_INVALID,
  ],
  [DOSSIER_STATUSES.STATUTES_SIGNED]: [
    DOSSIER_STATUSES.PAYMENT_PENDING,
    DOSSIER_STATUSES.MANUAL_REVIEW_REQUIRED,
  ],
  [DOSSIER_STATUSES.PAYMENT_PENDING]: [
    DOSSIER_STATUSES.PAYMENT_CONFIRMED,
    DOSSIER_STATUSES.PAYMENT_FAILED,
    DOSSIER_STATUSES.CANCELLED_BY_CLIENT,
  ],
  [DOSSIER_STATUSES.PAYMENT_FAILED]: [
    DOSSIER_STATUSES.PAYMENT_PENDING,
    DOSSIER_STATUSES.CANCELLED_BY_CLIENT,
  ],
  [DOSSIER_STATUSES.PAYMENT_CONFIRMED]: [
    DOSSIER_STATUSES.DOSSIER_PREPARATION,
  ],
  [DOSSIER_STATUSES.DOSSIER_PREPARATION]: [
    DOSSIER_STATUSES.CLIENT_VALIDATION_REQUIRED,
  ],
  [DOSSIER_STATUSES.CLIENT_VALIDATION_REQUIRED]: [
    DOSSIER_STATUSES.CLIENT_VALIDATED,
    DOSSIER_STATUSES.DOCUMENTS_MISSING_OR_INVALID,
  ],
  [DOSSIER_STATUSES.CLIENT_VALIDATED]: [
    DOSSIER_STATUSES.READY_FOR_FILING,
  ],
  [DOSSIER_STATUSES.READY_FOR_FILING]: [
    DOSSIER_STATUSES.FILED_TO_GUICHET_UNIQUE,
  ],
  [DOSSIER_STATUSES.FILED_TO_GUICHET_UNIQUE]: [
    DOSSIER_STATUSES.UNDER_ADMINISTRATION_REVIEW,
  ],
  [DOSSIER_STATUSES.UNDER_ADMINISTRATION_REVIEW]: [
    DOSSIER_STATUSES.REGULARIZATION_REQUESTED,
    DOSSIER_STATUSES.ACCEPTED,
    DOSSIER_STATUSES.REJECTED,
  ],
  [DOSSIER_STATUSES.REGULARIZATION_REQUESTED]: [
    DOSSIER_STATUSES.REGULARIZATION_SUBMITTED,
    DOSSIER_STATUSES.ABANDONED,
  ],
  [DOSSIER_STATUSES.REGULARIZATION_SUBMITTED]: [
    DOSSIER_STATUSES.UNDER_ADMINISTRATION_REVIEW,
  ],
  [DOSSIER_STATUSES.ACCEPTED]: [DOSSIER_STATUSES.OFFICIAL_DOCUMENTS_AVAILABLE],
  [DOSSIER_STATUSES.OFFICIAL_DOCUMENTS_AVAILABLE]: [DOSSIER_STATUSES.COMPLETED],
  [DOSSIER_STATUSES.CANCELLED_BY_CLIENT]: [DOSSIER_STATUSES.REFUNDED],
  [DOSSIER_STATUSES.MANUAL_REVIEW_REQUIRED]: [
    DOSSIER_STATUSES.DOCUMENTS_UNDER_REVIEW,
    DOSSIER_STATUSES.CLIENT_VALIDATION_REQUIRED,
    DOSSIER_STATUSES.READY_FOR_FILING,
  ],
});

const canTransition = (from, to) => {
  if (from === to) return true;
  return Boolean(ALLOWED_TRANSITIONS[from]?.includes(to));
};

export {
  DOSSIER_STATUSES,
  canTransition,
};
