export const COMPARATOR_DISCLAIMER_SHORT =
  'Ce questionnaire fournit une orientation générale à partir de vos réponses. Il ne constitue pas un conseil juridique, fiscal, social ou comptable personnalisé. Le choix final doit être confirmé selon votre situation et, si nécessaire, avec un professionnel.';

export const COMPARATOR_DISCLAIMER_RESULT =
  'Cette recommandation est une aide à la décision basée sur vos réponses. Elle ne constitue pas un conseil juridique, fiscal, social ou comptable personnalisé. Le choix final doit être confirmé selon votre situation.';

export const COMPARATOR_TRUST_LINE = [
  'Orientation indicative',
  'Sans engagement',
  'Données juridiques vulgarisées',
];

export const COMPARATOR_EDUCATION_CARDS = [
  {
    key: 'why',
    title: 'Pourquoi la forme juridique compte ?',
    text: 'Elle détermine votre responsabilité, votre fiscalité, votre protection sociale et la capacité de votre structure à accueillir des associés ou des investisseurs.',
  },
  {
    key: 'criteria',
    title: 'Ce que le comparateur prend en compte',
    text: 'Nombre de fondateurs, nature de l’activité, chiffre d’affaires visé, charges, risque, image recherchée, formalités acceptées et préférences sociales.',
  },
  {
    key: 'next',
    title: 'Ce que Greffio peut faire ensuite',
    text: 'Générer vos statuts, préparer votre dossier de création, publier l’annonce légale et suivre le dépôt au greffe jusqu’à l’immatriculation.',
  },
];

export const LEGAL_FORM_IDEAL_FOR = {
  micro: 'Tester seul, peu de charges',
  ei: 'Indépendant seul',
  sasu: 'Projet seul ambitieux',
  sas: 'Projet à plusieurs, startup',
  eurl: 'Société seul, cadre classique',
  sarl: 'Commerce, PME, famille',
  sci: 'Immobilier à plusieurs',
  association_1901: 'Projet non lucratif',
  sa: 'Grande entreprise structurée',
  snc: 'Cas commercial spécifique',
};

export const LEGAL_FORM_FEATURE_BADGES = {
  micro: ['Simple'],
  ei: ['Simple'],
  sasu: ['Flexible', 'Investisseurs', 'Responsabilité limitée'],
  sas: ['Flexible', 'Investisseurs', 'Responsabilité limitée'],
  eurl: ['Responsabilité limitée'],
  sarl: ['Responsabilité limitée'],
  sci: ['Immobilier'],
  association_1901: ['Non lucratif'],
  sa: ['Investisseurs', 'Responsabilité limitée'],
  snc: [],
};

export const COMPARATOR_MICRO_THRESHOLDS_2026 = {
  goods: 203_100,
  services: 83_600,
  mixedTotal: 203_100,
  mixedServicesMax: 83_600,
};

export const FIT_LEVEL_LABELS = {
  strong: 'Très adapté',
  good: 'Adapté',
  possible: 'Possible avec vigilance',
  weak: 'À étudier',
  avoid: 'Peu adapté',
};

export const AVAILABILITY_LABELS = {
  available_now: 'Disponible sur Greffio',
  coming_soon: 'Bientôt disponible',
  manual_quote: 'Sur devis',
};

const form = (entry) => ({
  investorFriendlyLabel: 'Non',
  ...entry,
});

export const LEGAL_FORM_COMPARATOR_FORMS = {
  micro: form({
    key: 'micro',
    label: 'Micro-entreprise',
    longLabel: 'Micro-entreprise',
    category: 'Entrepreneur individuel',
    availabilityKey: 'micro',
    hasGreffioStatutes: false,
    minAssociates: 1,
    maxAssociates: 1,
    capital: 'Aucun capital social',
    liability: 'Patrimoine personnel et professionnel automatiquement séparés',
    taxDefault: 'IR avec régime micro-BIC ou micro-BNC selon l’activité',
    social: 'Régime micro-social simplifié',
    accounting: 'Comptabilité très allégée',
    complexity: 1,
    fundraising: 'Non',
    shortPitch: 'La solution la plus simple pour démarrer seul, surtout si l’activité est légère et avec peu de charges.',
  }),
  ei: form({
    key: 'ei',
    label: 'Entreprise individuelle',
    longLabel: 'Entreprise individuelle classique',
    category: 'Entrepreneur individuel',
    availabilityKey: 'ei',
    hasGreffioStatutes: false,
    minAssociates: 1,
    maxAssociates: 1,
    capital: 'Aucun capital social',
    liability: 'Patrimoines personnel et professionnel automatiquement séparés',
    taxDefault: 'IR par défaut ; option possible à l’IS via assimilation à une EURL',
    social: 'Travailleur indépendant',
    accounting: 'Variable selon le régime fiscal et l’activité',
    complexity: 2,
    fundraising: 'Non',
    shortPitch: 'Une structure individuelle simple, plus large que la micro-entreprise, sans création de société.',
  }),
  sasu: form({
    key: 'sasu',
    label: 'SASU',
    longLabel: 'Société par actions simplifiée unipersonnelle',
    category: 'Société commerciale',
    availabilityKey: 'sasu',
    hasGreffioStatutes: true,
    minAssociates: 1,
    maxAssociates: 1,
    capital: 'Capital libre, souvent possible à partir de 1 €',
    liability: 'Responsabilité en principe limitée aux apports',
    taxDefault: 'IS par défaut ; option temporaire à l’IR possible sous conditions',
    social: 'Président assimilé salarié s’il est rémunéré, sans assurance chômage automatique',
    accounting: 'Comptabilité commerciale complète',
    complexity: 4,
    fundraising: 'Oui',
    shortPitch: 'La forme la plus naturelle pour un projet seul, ambitieux, moderne et potentiellement scalable.',
  }),
  sas: form({
    key: 'sas',
    label: 'SAS',
    longLabel: 'Société par actions simplifiée',
    category: 'Société commerciale',
    availabilityKey: 'sas',
    hasGreffioStatutes: true,
    minAssociates: 2,
    maxAssociates: null,
    capital: 'Capital libre, souvent possible à partir de 1 €',
    liability: 'Responsabilité en principe limitée aux apports',
    taxDefault: 'IS par défaut ; option temporaire à l’IR possible sous conditions',
    social: 'Président assimilé salarié s’il est rémunéré, sans assurance chômage automatique',
    accounting: 'Comptabilité commerciale complète',
    complexity: 4,
    fundraising: 'Oui',
    shortPitch: 'La structure de référence pour un projet à plusieurs avec besoin de flexibilité et d’évolution.',
  }),
  eurl: form({
    key: 'eurl',
    label: 'EURL',
    longLabel: 'Entreprise unipersonnelle à responsabilité limitée',
    category: 'Société commerciale',
    availabilityKey: 'eurl',
    hasGreffioStatutes: true,
    minAssociates: 1,
    maxAssociates: 1,
    capital: 'Pas de capital minimum légal usuel',
    liability: 'Responsabilité en principe limitée aux apports',
    taxDefault: 'IR par défaut si associé unique personne physique ; option possible à l’IS',
    social: 'Gérant associé unique généralement travailleur non salarié',
    accounting: 'Comptabilité commerciale complète',
    complexity: 3,
    fundraising: 'Faible',
    shortPitch: 'Une société unipersonnelle encadrée, souvent adaptée aux activités classiques avec dirigeant TNS.',
  }),
  sarl: form({
    key: 'sarl',
    label: 'SARL',
    longLabel: 'Société à responsabilité limitée',
    category: 'Société commerciale',
    availabilityKey: 'sarl',
    hasGreffioStatutes: true,
    minAssociates: 2,
    maxAssociates: 100,
    capital: 'Pas de capital minimum légal usuel',
    liability: 'Responsabilité en principe limitée aux apports',
    taxDefault: 'IS par défaut ; option à l’IR possible dans certains cas',
    social: 'Gérant majoritaire TNS ; gérant minoritaire ou égalitaire assimilé salarié s’il est rémunéré',
    accounting: 'Comptabilité commerciale complète',
    complexity: 3,
    fundraising: 'Moyenne / faible',
    shortPitch: 'Une société commerciale rassurante et encadrée, adaptée aux commerces, artisans et PME familiales.',
  }),
  sci: form({
    key: 'sci',
    label: 'SCI',
    longLabel: 'Société civile immobilière',
    category: 'Société civile',
    availabilityKey: 'sci',
    hasGreffioStatutes: true,
    minAssociates: 2,
    maxAssociates: null,
    capital: 'Pas de capital minimum légal usuel',
    liability: 'Responsabilité indéfinie des associés, en proportion de leurs parts',
    taxDefault: 'IR par défaut ; option possible à l’IS',
    social: 'Dépend de la situation du gérant et de l’activité',
    accounting: 'Variable selon régime fiscal et option IS éventuelle',
    complexity: 3,
    fundraising: 'Non',
    shortPitch: 'La forme typique pour organiser la détention ou la gestion d’un patrimoine immobilier à plusieurs.',
  }),
  association_1901: form({
    key: 'association_1901',
    label: 'Association loi 1901',
    longLabel: 'Association loi 1901',
    category: 'Non lucratif',
    availabilityKey: 'association-1901',
    hasGreffioStatutes: false,
    minAssociates: 2,
    maxAssociates: null,
    capital: 'Pas de capital social',
    liability: 'Structure distincte, vigilance sur la responsabilité des dirigeants selon gestion',
    taxDefault: 'En principe non lucrative ; fiscalisation possible en cas d’activité lucrative',
    social: 'Dirigeants souvent bénévoles ; salariés possibles',
    accounting: 'Variable selon taille, activité, subventions et fiscalisation',
    complexity: 2,
    fundraising: 'Non en capital',
    shortPitch: 'La structure adaptée aux projets non lucratifs, collectifs ou associatifs.',
  }),
  sa: form({
    key: 'sa',
    label: 'SA',
    longLabel: 'Société anonyme',
    category: 'Société commerciale',
    availabilityKey: 'sa',
    hasGreffioStatutes: false,
    minAssociates: 2,
    maxAssociates: null,
    capital: 'Capital social minimum de 37 000 €',
    liability: 'Responsabilité en principe limitée aux apports',
    taxDefault: 'IS',
    social: 'Dirigeants assimilés salariés selon fonctions',
    accounting: 'Comptabilité et gouvernance très structurées',
    complexity: 5,
    fundraising: 'Oui',
    shortPitch: 'Une forme lourde et très structurée, rarement pertinente pour une création simple.',
  }),
  snc: form({
    key: 'snc',
    label: 'SNC',
    longLabel: 'Société en nom collectif',
    category: 'Société commerciale spécifique',
    availabilityKey: 'snc',
    hasGreffioStatutes: false,
    minAssociates: 2,
    maxAssociates: null,
    capital: 'Pas de capital minimum légal usuel',
    liability: 'Responsabilité solidaire et indéfinie des associés',
    taxDefault: 'IR par défaut ; option possible à l’IS',
    social: 'Associés généralement travailleurs non salariés',
    accounting: 'Comptabilité commerciale',
    complexity: 3,
    fundraising: 'Faible',
    shortPitch: 'Une forme spécifique, engageante, à recommander rarement dans un comparateur généraliste.',
  }),
};

export const LEGAL_FORM_REASONS = {
  micro: [
    'Vous exercez seul.',
    'Vous cherchez une solution simple à mettre en place.',
    'Votre chiffre d’affaires prévu reste compatible avec un démarrage léger.',
    'Vos charges semblent limitées.',
    'Vous ne prévoyez pas de levée de fonds.',
  ],
  ei: [
    'Vous exercez seul.',
    'Vous souhaitez rester dans une structure individuelle.',
    'Vous voulez plus de souplesse que la micro-entreprise selon votre régime fiscal.',
    'Vous n’avez pas besoin d’associés ni d’investisseurs.',
  ],
  sasu: [
    'Vous êtes seul au lancement.',
    'Vous recherchez une image professionnelle forte.',
    'Votre projet peut évoluer vers une SAS avec associés.',
    'La structure est adaptée aux projets numériques, premium ou scalables.',
    'Elle reste cohérente si vous envisagez une levée de fonds plus tard.',
  ],
  sas: [
    'Vous êtes plusieurs associés.',
    'Vous avez besoin d’une gouvernance flexible.',
    'Votre projet peut accueillir des investisseurs.',
    'La forme est adaptée aux startups et projets de croissance.',
    'Elle facilite l’organisation statutaire sur mesure.',
  ],
  eurl: [
    'Vous êtes seul.',
    'Vous voulez une société avec responsabilité limitée.',
    'Vous préférez un cadre plus classique que la SASU.',
    'Le régime de travailleur non salarié peut être pertinent selon votre situation.',
  ],
  sarl: [
    'Vous êtes plusieurs associés.',
    'Votre projet ressemble à une PME, un commerce, une activité artisanale ou familiale.',
    'Vous préférez un cadre légal plus encadré.',
    'La forme est connue et rassurante pour de nombreuses activités traditionnelles.',
  ],
  sci: [
    'Votre projet concerne principalement l’immobilier.',
    'Vous souhaitez organiser la détention d’un bien à plusieurs.',
    'La SCI est couramment utilisée pour gérer ou transmettre un patrimoine immobilier.',
    'Elle est plus pertinente pour la détention immobilière que pour une activité commerciale classique.',
  ],
  association_1901: [
    'Votre projet semble non lucratif.',
    'Vous ne cherchez pas à distribuer de bénéfices.',
    'La logique collective ou communautaire est centrale.',
    'La structure associative est adaptée aux projets culturels, sociaux, éducatifs, sportifs ou citoyens.',
  ],
  sa: [
    'Votre projet semble nécessiter une gouvernance très structurée.',
    'La SA peut convenir à de grandes entreprises ou à des projets avec nombreux actionnaires.',
    'Elle reste rarement nécessaire pour un lancement simple.',
  ],
  snc: [
    'La SNC peut être pertinente dans certains cas commerciaux très spécifiques.',
    'Elle suppose une relation de confiance forte entre associés.',
  ],
};

export const LEGAL_FORM_CAUTIONS = {
  micro: [
    'Les seuils de chiffre d’affaires doivent être surveillés.',
    'Les charges ne sont pas déduites au réel comme dans une société au régime réel.',
    'La forme n’est pas adaptée aux associés ni aux investisseurs.',
    'L’image peut être moins structurée pour certains clients ou partenaires.',
  ],
  ei: [
    'L’entreprise individuelle ne permet pas d’avoir des associés.',
    'Elle n’est pas adaptée à une levée de fonds en capital.',
    'Le choix entre régime réel, micro éventuel et option IS doit être vérifié.',
  ],
  sasu: [
    'La gestion est plus lourde qu’une micro-entreprise.',
    'La comptabilité commerciale complète est nécessaire.',
    'Les cotisations sociales du président rémunéré peuvent être élevées.',
    'Les statuts doivent être rédigés avec soin.',
  ],
  sas: [
    'La grande liberté statutaire suppose des statuts bien rédigés.',
    'La gouvernance doit être anticipée entre associés.',
    'La comptabilité et les formalités sont plus lourdes qu’en entreprise individuelle.',
  ],
  eurl: [
    'Moins naturelle pour une levée de fonds qu’une SASU.',
    'Le régime social TNS doit être comparé selon la rémunération souhaitée.',
    'La transformation ou l’entrée d’investisseurs peut être moins fluide.',
  ],
  sarl: [
    'Moins flexible qu’une SAS pour organiser une gouvernance sur mesure.',
    'Moins naturelle pour les levées de fonds importantes.',
    'Les règles de gérance et de majorité doivent être anticipées.',
  ],
  sci: [
    'La SCI n’est pas conçue pour une activité commerciale classique.',
    'Les associés peuvent être responsables indéfiniment des dettes sociales.',
    'Le choix IR/IS doit être étudié attentivement.',
  ],
  association_1901: [
    'Une association n’est pas faite pour distribuer des bénéfices.',
    'Une activité lucrative peut entraîner des conséquences fiscales.',
    'Le modèle économique doit être compatible avec le non lucratif.',
  ],
  sa: [
    'La SA est lourde à créer et à administrer.',
    'Le capital minimum est élevé.',
    'Elle est rarement adaptée à un créateur seul ou à une petite structure.',
  ],
  snc: [
    'Les associés sont responsables solidairement et indéfiniment.',
    'La forme est très engageante patrimonialement.',
    'Elle doit rarement être recommandée sans accompagnement professionnel.',
  ],
};

export const LEGAL_FORM_COMPARATOR_QUESTIONS = [
  {
    id: 'founders_count',
    title: 'Combien de personnes porteront le projet au capital ?',
    subtitle: 'Certaines formes sont réservées à une personne seule, d’autres nécessitent au moins deux associés.',
    type: 'single_choice',
    required: true,
    options: [
      { value: 'solo', label: 'Je suis seul', description: 'Vous serez l’unique associé ou exploitant.' },
      { value: 'two', label: 'Nous sommes deux', description: 'Deux personnes au capital dès le départ.' },
      { value: 'three_plus', label: 'Nous sommes trois ou plus', description: 'Une équipe fondatrice élargie.' },
      { value: 'not_sure', label: 'Je ne sais pas encore', description: 'Le nombre d’associés reste à confirmer.' },
    ],
  },
  {
    id: 'activity_type',
    title: 'Quelle est la nature principale de l’activité ?',
    subtitle: 'L’activité influence fortement la forme juridique adaptée.',
    type: 'single_choice',
    required: true,
    options: [
      { value: 'freelance_services', label: 'Freelance, conseil, prestation intellectuelle' },
      { value: 'commerce', label: 'Commerce, achat-revente, boutique' },
      { value: 'craft', label: 'Artisanat' },
      { value: 'saas_startup', label: 'SaaS, startup, produit numérique' },
      { value: 'liberal', label: 'Profession libérale' },
      { value: 'regulated_liberal', label: 'Profession libérale réglementée' },
      { value: 'real_estate', label: 'Immobilier ou détention d’un bien' },
      { value: 'non_profit', label: 'Projet associatif ou non lucratif' },
      { value: 'agricultural', label: 'Activité agricole' },
      { value: 'holding_group', label: 'Holding, filiale ou groupe' },
      { value: 'other', label: 'Autre activité' },
    ],
  },
  {
    id: 'revenue_12m',
    title: 'Quel chiffre d’affaires annuel visez-vous à court terme ?',
    subtitle: 'Cela permet notamment d’identifier si le régime micro reste cohérent.',
    type: 'single_choice',
    required: true,
    options: [
      { value: 'under_15000', label: 'Moins de 15 000 €' },
      { value: 'under_50000', label: 'Moins de 50 000 €' },
      { value: 'under_83600', label: 'Moins de 83 600 €' },
      { value: 'under_203100', label: 'Moins de 203 100 €' },
      { value: 'above_203100', label: 'Plus de 203 100 €' },
      { value: 'unknown', label: 'Je ne sais pas encore' },
    ],
  },
  {
    id: 'expenses_level',
    title: 'Votre activité aura-t-elle beaucoup de charges à déduire ?',
    subtitle: 'Exemples : achats, stock, matériel, logiciels, publicité, sous-traitance, déplacements.',
    type: 'single_choice',
    required: true,
    options: [
      { value: 'low', label: 'Très peu de charges', description: 'Activité légère, peu d’achats ou d’équipement.' },
      { value: 'medium', label: 'Charges modérées', description: 'Quelques achats, outils ou prestataires réguliers.' },
      { value: 'high', label: 'Charges importantes', description: 'Stock, matériel, locaux ou sous-traitance significatifs.' },
      { value: 'unknown', label: 'Je ne sais pas encore' },
    ],
  },
  {
    id: 'fundraising',
    title: 'Pensez-vous faire entrer des investisseurs ou lever des fonds ?',
    subtitle: 'Les formes par actions sont généralement plus adaptées aux investisseurs.',
    type: 'single_choice',
    required: true,
    options: [
      { value: 'yes_short_term', label: 'Oui, à court terme', description: 'Une levée de fonds est prévue rapidement.' },
      { value: 'maybe_later', label: 'Peut-être plus tard', description: 'L’option doit rester ouverte.' },
      { value: 'no', label: 'Non', description: 'Pas d’investisseurs externes envisagés.' },
    ],
  },
  {
    id: 'risk_level',
    title: 'Quel est le niveau de risque financier ou juridique ?',
    subtitle: 'Contrats importants, dettes, stock, salariés ou responsabilités augmentent le besoin de structuration.',
    type: 'single_choice',
    required: true,
    options: [
      { value: 'low', label: 'Faible', description: 'Peu d’engagements financiers ou contractuels.' },
      { value: 'medium', label: 'Modéré', description: 'Quelques contrats ou engagements à suivre.' },
      { value: 'high', label: 'Élevé', description: 'Dettes, stock, salariés ou contrats importants.' },
    ],
  },
  {
    id: 'image_priority',
    title: 'Quelle importance accordez-vous à l’image professionnelle ?',
    subtitle: 'Certains projets ont besoin d’une structure plus crédible vis-à-vis des clients, banques ou partenaires.',
    type: 'single_choice',
    required: true,
    options: [
      { value: 'basic', label: 'Peu important, je veux surtout aller vite' },
      { value: 'professional', label: 'Important, je veux être crédible' },
      { value: 'premium', label: 'Très important, je veux une image premium ou startup' },
    ],
  },
  {
    id: 'admin_tolerance',
    title: 'Quel niveau de formalités acceptez-vous ?',
    subtitle: 'Plus une structure est complète, plus elle implique généralement de formalités et de comptabilité.',
    type: 'single_choice',
    required: true,
    options: [
      { value: 'minimal', label: 'Le minimum possible', description: 'Déclarations simples, gestion très allégée.' },
      { value: 'moderate', label: 'Un niveau raisonnable', description: 'Une comptabilité encadrée mais accessible.' },
      { value: 'advanced', label: 'Une structure plus complète si elle est adaptée', description: 'Statuts, comptabilité commerciale et formalités assumés.' },
    ],
  },
  {
    id: 'social_preference',
    title: 'Quelle protection sociale souhaitez-vous pour le dirigeant ?',
    subtitle: 'À ce stade, il s’agit seulement d’une orientation générale, pas d’une optimisation personnalisée.',
    type: 'single_choice',
    required: true,
    options: [
      { value: 'low_contributions', label: 'Des cotisations plus faibles', description: 'Régime des indépendants, charges souvent réduites.' },
      { value: 'better_protection', label: 'Une protection proche du régime général', description: 'Couverture étendue, cotisations souvent plus élevées.' },
      { value: 'no_preference', label: 'Je n’ai pas de préférence' },
    ],
  },
  {
    id: 'profit_distribution',
    title: 'Souhaitez-vous pouvoir vous verser des dividendes ?',
    subtitle: 'Les dividendes supposent généralement une société, pas une entreprise individuelle classique.',
    type: 'single_choice',
    required: true,
    options: [
      { value: 'yes', label: 'Oui', description: 'Distribuer une partie des bénéfices en dividendes.' },
      { value: 'maybe', label: 'Peut-être', description: 'À envisager selon les résultats.' },
      { value: 'no', label: 'Non, je veux surtout me rémunérer simplement' },
    ],
  },
  {
    id: 'timeline',
    title: 'Quel est votre calendrier ?',
    subtitle: 'Cela permet d’adapter le parcours suivant : statuts, dossier, devis ou simple comparaison.',
    type: 'single_choice',
    required: true,
    options: [
      { value: 'now', label: 'Je veux démarrer maintenant', description: 'Prêt à lancer les démarches immédiatement.' },
      { value: 'this_month', label: 'Je veux lancer ce mois-ci', description: 'Démarrage prévu dans les prochaines semaines.' },
      { value: 'exploring', label: 'Je compare encore', description: 'En phase de réflexion et de comparaison.' },
    ],
  },
];

export const LEGAL_FORM_GLOSSARY = [
  { term: 'Forme juridique', definition: 'Cadre légal dans lequel une activité est exercée : EI, micro-entreprise, SASU, SAS, EURL, SARL, SCI, association, etc.' },
  { term: 'Régime fiscal', definition: 'Mode d’imposition des bénéfices : impôt sur le revenu, impôt sur les sociétés, régime micro ou réel.' },
  { term: 'IR', definition: 'Impôt sur le revenu. Les bénéfices sont imposés au niveau de la personne physique ou des associés selon les cas.' },
  { term: 'IS', definition: 'Impôt sur les sociétés. Les bénéfices sont imposés au niveau de la société.' },
  { term: 'Responsabilité limitée', definition: 'Principe selon lequel l’associé n’est en principe responsable des dettes sociales qu’à hauteur de ses apports, sauf exceptions.' },
  { term: 'Assimilé salarié', definition: 'Statut social de certains dirigeants affiliés au régime général, sans assurance chômage automatique pour le mandataire social.' },
  { term: 'Travailleur non salarié', definition: 'Dirigeant ou entrepreneur affilié au régime des indépendants.' },
  { term: 'Capital social', definition: 'Somme ou valeur des apports réalisés par les associés ou actionnaires lors de la création ou d’une augmentation de capital.' },
  { term: 'Statuts', definition: 'Document fondateur d’une société qui fixe ses règles de fonctionnement.' },
  { term: 'Guichet unique', definition: 'Plateforme officielle permettant d’effectuer les formalités de création, modification ou cessation d’entreprise.' },
];

export const LEGAL_FORM_FAQ = [
  {
    question: 'Quelle est la différence entre micro-entreprise et société ?',
    answer: 'La micro-entreprise est un régime simplifié de l’entreprise individuelle. Elle permet de démarrer seul avec des formalités allégées. Une société comme une SASU, SAS, EURL ou SARL crée une personne morale distincte, avec statuts, capital et comptabilité plus complète.',
  },
  {
    question: 'La SASU est-elle toujours meilleure qu’une EURL ?',
    answer: 'Non. La SASU convient souvent aux projets modernes, premium ou susceptibles d’évoluer avec des investisseurs. L’EURL peut être plus adaptée à un entrepreneur seul qui souhaite un cadre encadré et un régime social de travailleur non salarié.',
  },
  {
    question: 'Peut-on changer de forme juridique plus tard ?',
    answer: 'Oui, une entreprise peut évoluer, mais cela implique des formalités, parfois une transformation ou une création de société. Il vaut mieux choisir une structure cohérente dès le départ si le projet prévoit des associés, des investisseurs ou un actif immobilier.',
  },
  {
    question: 'Quelle forme choisir pour une startup ?',
    answer: 'Pour une startup ou un projet SaaS, la SASU si le fondateur est seul ou la SAS s’il y a plusieurs associés sont souvent les formes les plus naturelles. Cela doit toutefois être confirmé selon la situation exacte du projet.',
  },
  {
    question: 'Quelle forme choisir pour un projet immobilier ?',
    answer: 'Pour détenir ou gérer un bien immobilier à plusieurs, la SCI est souvent la forme la plus étudiée. Elle n’est cependant pas adaptée à toutes les activités immobilières commerciales. Le choix entre IR et IS doit aussi être analysé avec prudence.',
  },
  {
    question: 'Quelle forme choisir pour tester une activité ?',
    answer: 'Pour tester seul une activité simple avec peu de charges, la micro-entreprise peut être pertinente. Si le projet est plus ambitieux ou nécessite une image structurée, une société comme la SASU ou l’EURL peut être plus cohérente.',
  },
  {
    question: 'Greffio remplace-t-il un avocat ou un expert-comptable ?',
    answer: 'Non. Greffio aide à comprendre, préparer et réaliser des démarches administratives. Les recommandations affichées par ce questionnaire sont indicatives et ne remplacent pas un conseil personnalisé.',
  },
  {
    question: 'Pourquoi certaines formes sont-elles sur devis ?',
    answer: 'Certaines structures sont plus spécifiques : professions réglementées, groupes, holdings, formes agricoles ou montages complexes. Elles nécessitent souvent une analyse particulière avant d’être traitées correctement.',
  },
];

export const COMPARATOR_FORM_ORDER = [
  'micro', 'ei', 'sasu', 'sas', 'eurl', 'sarl', 'sci', 'association_1901', 'sa', 'snc',
];
