import {
  apportsWilliam,
  article,
  buildWilliamCover,
  buildWilliamDefinitions,
  buildWilliamObjetActe,
  buildWilliamSignatures,
  buildWilliamSoussignes,
  capitalRepartitionWilliam,
  legalTitle,
  objetSocialWilliam,
  sigleSuffix,
} from './williamHelpers.js';
import { buildStandardAnnexes } from '../shared/annexes.js';

export const buildWilliamSasDocument = (data) => {
  const blocks = [
    ...buildWilliamSoussignes(data),
    ...buildWilliamDefinitions(data),
    ...buildWilliamObjetActe(data),
    legalTitle('TITRE I – FORMATION DE LA SOCIÉTÉ'),
    article(1, 'Dénomination', `Il est formé une Société par Actions Simplifiée dénommée ${data.denomination}${sigleSuffix(data)}.`),
    article(2, 'Objet social', objetSocialWilliam(data)),
    article(3, 'Siège social', [
      `Le siège social est fixé au ${data.seat.full}${data.domiciliation ? `, chez ${data.domiciliation}` : ''}.`,
      data.mailingAddress ? `\n\nLe courrier peut être adressé au : ${data.mailingAddress}.` : '',
    ].join('')),
    article(4, 'Durée', `La Société est constituée pour une durée de ${data.duree || '99 année'} à compter de son immatriculation au Registre du Commerce et des Sociétés, sauf dissolution anticipée ou prorogation.`),
    article(5, 'Capital social et exercice social', [
      `Le capital social est fixé à la somme de ${data.capital} euros, divisé en ${data.nombreTitres} actions de ${data.valeurNominale} euro chacune.`,
      data.capitalType === 'Variable' || data.capitalVariable
        ? `\n\nLe capital est variable conformément aux articles L.231-1 à L.231-8 du Code de commerce, avec un minimum de ${data.capitalMin || data.capital} euros et un maximum de ${data.capitalMax || '5 000 000'} euros.\n\nLes augmentations ou réductions dans la fourchette du capital variable sont décidées par décision collective ordinaire des associés. Celles-ci sont constatées par le Président au registre, sans modification statutaire.`
        : '',
      `\n\nLa répartition du capital est la suivante :\n\n${capitalRepartitionWilliam(data)}`,
      `\n\nL'exercice social se termine le ${data.exerciceFin} de chaque année et recommence le jour suivant.`,
      data.premierExerciceFin ? `\nPar exception, le premier exercice sera clôturé le ${data.premierExerciceFin}.` : '',
    ].join('')),
    article(6, 'L\'associé mineur émancipé ou non émancipé', [
      "L'associé mineur émancipé peut exercer pleinement ses droits d'associé dans la Société, notamment en matière de vote, de gestion et de représentation, conformément aux dispositions légales en vigueur.",
      '',
      "L'émancipation ne dispense pas, en conséquence, l'associé mineur des obligations statutaires et légales liées à sa qualité d'associé.",
      "L'associé mineur non émancipé, exerce ses droits sociaux par l'intermédiaire de ses représentants légaux.",
      'Les représentants légaux agissent pour le compte de l\'associé mineur dans tous les actes relatifs à la Société, notamment vote, souscription, cession, décision collective.',
      "Toute décision engageant significativement le patrimoine de l'associé mineur devra respecter les dispositions du Code civil relatives à l'administration légale des biens des mineurs.",
    ].join('\n')),
    article(7, 'Apports', apportsWilliam(data)),
    legalTitle('TITRE II – ADMINISTRATION & ORGANISATION'),
    article(8, 'Administration', [
      'La société est dirigée par un Président nommé par décision collective des associés.',
      '',
      `Le Président est ${data.president || data.director}.`,
      data.directeurGeneral && data.directeurGeneral !== 'Aucun'
        ? `Le Directeur Général est ${data.directeurGeneral}.`
        : '',
    ].filter(Boolean).join('\n')),
    article(9, 'Pouvoirs du Président et du Directeur Général', [
      "Le Président représente la Société à l'égard des tiers.",
      '',
      "Il est investi, en vertu de la Loi, des pouvoirs les plus étendus pour agir en toutes circonstances au nom de la Société; il les exerce dans la limite de l'objet social et sous réserve de ceux expressément attribués par la loi aux Associés.",
      '',
      "Dans les rapports entre Associés, le Président peut accomplir tous actes de direction, de disposition, de gestion et d'administration de la Société, dans la limite de l'objet social et des prérogatives des décisions d'Associés.",
      '',
      data.directeurGeneral && data.directeurGeneral !== 'Aucun'
        ? "Le Directeur Général est investi des mêmes pouvoirs représentatifs que le Président pour agir en toutes circonstances au nom de la Société; il les exerce dans la limite de l'objet social et sous réserve de ceux expressément attribués par la Loi aux Associés."
        : '',
      '',
      "Le Président est nommé et révoqué par décision collective extraordinaire des Associés représentant plus de 75% des actions.",
      '',
      "Si cette majorité n'est pas obtenue sur première consultation, les Associés sont, selon le cas, convoqués ou consultés une seconde fois, et les décisions sont prises à 65% des actions représentées.",
      '',
      'Les fonctions de Président et de Directeur Général sont exercées sans limitation de durée. Elles prennent fin par décès, démission, révocation pour juste motif, incapacité ou faillite personnelle.',
      '',
      'Le Directeur Général est nommé et peut être révoqué à tout moment par décision du Président. La révocation doit être motivée, notamment pour faute grave, avec indemnisation possible.',
      '',
      'Toute limitation par les présents statuts des pouvoirs des fonctions de Président et de Directeur général est inopposable aux tiers.',
    ].filter(Boolean).join('\n\n')),
    article(10, 'Rémunération', [
      'Les associés déterminent librement la rémunération du Président et des dirigeants.',
      '',
      "Toute rémunération fait l'objet d'une décision collective ordinaire.",
      '',
      'Les dirigeants peuvent être rémunérés ou exercer leurs fonctions sans être rémunérés selon décision des associés.',
    ].join('\n')),
    legalTitle('TITRE III – DÉCISIONS COLLECTIVES'),
    article(11, 'Décisions collectives des Associés', [
      'Les décisions collectives des associés sont prises dans les conditions de quorum et de majorité prévues ci-contre, et selon la loi.',
      '',
      'Les décisions relevant de la gestion courante de la société sont prises en Assemblée Générale Ordinaire (AGO).',
      '',
      'Les décisions entraînant une modification des statuts sont prises en Assemblée Générale Extraordinaire (AGE).',
      '',
      'Le quorum doit être de 50% des actions de la Société pour la validité des assemblées générales ordinaires.',
      '',
      'Les décisions ordinaires sont prises à la majorité de 60% des actions représentées.',
      '',
      'Au cours des assemblées générales extraordinaires, le quorum est fixé à 70 % des actions de la Société en première convocation, et 60% en deuxième convocation.',
      '',
      "En vertu du droit d'information des Associés, et de leur droit de préparer le vote, la seconde Assemblée Générale Extraordinaire portant sur le même ordre du jour peut être tenue le même jour, immédiatement après la constatation du défaut de quorum, à condition que cette éventualité ait été mentionnée dans la convocation initiale.",
      '',
      'Les décisions extraordinaires sont soumises à la majorité de 75% des actions représentées.',
    ].join('\n')),
    article(12, 'Consultation et convocation de l\'Assemblée Générale', [
      "La consultation par écrit, ou la convocation des Associés est prévue par les présents Statuts tels que suit.",
      '',
      "La consultation par écrit permet au Président de soumettre un projet de décision à chaque associé sans réunion physique. L'envoi se fait par tout moyen écrit permettant de prouver la réception (courrier avec avis de réception, remise en main propre ou e-mail avec accusé de réception). Chaque associé dispose d'un délai précisé dans la convocation pour répondre.",
      '',
      "La convocation à une assemblée générale ordinaire est effectuée par le Président, ou par tout associé représentant au moins 20% du capital social.",
      '',
      "La convocation à une assemblée générale extraordinaire est effectuée par le Président. Le Président peut décider de convoquer une AGE, notamment à la suite d'une demande écrite d'un ou plusieurs associés.",
      '',
      "Les convocations mentionnent l'ordre du jour, la date, l'heure et le lieu de l'assemblée. Elles sont transmises par tous moyens permettant de justifier sa réception (lettre recommandée avec avis de réception, par e-mail, ou remise en main propre).",
    ].join('\n')),
    legalTitle('TITRE IV – ACTIONS & MOUVEMENT DES TITRES'),
    article(13, 'Forme des actions / registre des mouvements', [
      'La propriété des actions est établie par leur inscription au nom des titulaires dans le registre de mouvement de titres tenu par le Président de la Société.',
      '',
      "Les registres peuvent être conservés soit au siège social, soit en tout autre lieu choisi par le Président, par le moyen de support papier ou numérique, en vertu de l'article L228-1 du Code de Commerce.",
      '',
      'Les registres sociétaires restent accessibles aux associés et aux autorités compétentes.',
      '',
      'Le Président est expressément habilité à constater et à inscrire chronologiquement dans ce registre toutes opérations relatives aux actions et au capital social, dans les limites du capital minimum et maximum fixés par les statuts.',
      '',
      "Ces opérations ne donnent pas lieu à modification des statuts ni à formalités de publicité extérieure tant que le capital demeure compris entre ces limites.",
    ].join('\n')),
    article(14, 'Inaliénabilité temporaire', [
      `Les actions sont inaliénables pendant une durée de ${data.inalienabiliteAnnees || 'cinq (5)'} année${Number(data.inalienabiliteAnnees) === 1 ? '' : 's'} à compter de l'immatriculation de la Société.`,
      'Pendant cette période, aucune cession, transmission ou nantissement ne pourra intervenir sans décision collective extraordinaire représentant au moins 75% des actions représentées.',
      "Cette clause est justifiée par la nécessité d'assurer la stabilité du capital et la continuité du projet social.",
    ].join('\n')),
    article(15, 'Droit de préemption', [
      "En cas de projet de cession d'actions à un tiers, les autres associés bénéficient d'un droit de préemption proportionnel à leur participation. Ils disposent d'un délai de trente (30) jours pour exercer ce droit.",
      "À défaut d'exercice, la cession pourra être réalisée sous réserve de l'agrément prévu aux statuts.",
    ].join('\n')),
    article(16, 'Agrément et cession des actions', [
      "Toute cession d'actions, qu'elle intervienne entre associés ou à des tiers, doit obtenir l'accord préalable des associés.",
      '',
      'Le projet de cession doit être notifié à la société par lettre recommandée avec accusé de réception.',
      '',
      "Dans les huit jours, le Président convoque une assemblée des associés ou procède à une consultation écrite pour statuer sur cette demande.",
      '',
      "La décision est communiquée dans un délai de trois mois : passé ce délai, l'agrément est considéré comme acquis.",
      "En cas de refus, la société ou les associés doivent racheter les actions dans un délai de trois mois, sauf si le cédant y renonce. L'agrément est accordé si les associés représentant plus de 75% des actions se prononcent favorablement.",
    ].join('\n')),
    article(17, 'Agrément et cession des actions', [
      'Un associé peut être exclu de la Société par décision collective extraordinaire représentant au moins 75% des actions représentées, l\'associé concerné ne prenant pas part au vote.',
      '',
      "L'exclusion peut être prononcée notamment en cas de :",
      '● Violation grave des statuts ;',
      '● Manquement grave à ses obligations;',
      '● Concurrence déloyale ou activité concurrente ;',
      '● Condamnation pénale incompatible avec l\'intérêt social ;',
      '● Perte de la qualité requise pour être associé ;',
      '● Comportement portant atteinte aux intérêts sociaux.',
      "L'associé concerné est préalablement informé par lettre recommandée et peut présenter ses observations.",
      '',
      "Les actions de l'associé exclu seront rachetées par la Société ou par les autres associés dans un délai de trois mois, à une valeur déterminée :",
      '● soit d\'un commun accord ;',
      '● soit par un expert désigné conformément à l\'article 1843-4 du Code civil.',
      "Jusqu'au rachat effectif, les droits financiers demeurent mais les droits politiques peuvent être suspendus.",
    ].join('\n')),
    article(18, 'Droit de sortie conjointe', [
      'En cas de cession par un associé détenant plus de 50% du capital, les autres associés pourront exiger que le cessionnaire acquière également leurs actions aux mêmes conditions.',
    ].join('\n')),
    legalTitle('TITRE V – FONCTIONNEMENT INTERNE'),
    article(19, 'Confidentialité', [
      'Tous les dirigeants, associés, employés, ainsi que toute personne exerçant des fonctions au sein de la Société ou collaborant ponctuellement avec elle (consultants, prestataires), sont tenus à la confidentialité concernant toutes informations commerciales, financières, techniques ou stratégiques sensibles.',
      '',
      'Toute divulgation à des tiers non habilités est interdite sans autorisation préalable du Président ou du Directeur Général, ou toute autre personne désignée par le Président.',
    ].join('\n')),
    article(20, 'Adoption d\'un règlement intérieur', [
      'Les associés peuvent adopter un règlement intérieur pour organiser le fonctionnement interne de la Société.',
      '',
      'Le règlement intérieur est voté à la majorité simple des associés, pour organiser les règles de fonctionnement interne, la discipline, la répartition des tâches, les organes de gestion et de décisions, et les procédures internes. Le règlement intérieur entre en vigueur dès son adoption, sauf disposition contraire.',
      '',
      'Toute modification du règlement intérieur est décidée à la majorité simple des associés.',
      '',
      'Une copie du règlement intérieur est remise à chaque associé et aux dirigeants concernés.',
    ].join('\n')),
    article(21, 'Pacte des Associés', [
      "Les Associés peuvent souscrire à un Pacte d'associés distinct des présents statuts visant à encadrer les modalités de leur coopération.",
    ].join('\n')),
    legalTitle('TITRE VI – RÉSULTATS & FIN DE VIE'),
    article(22, 'Affectation des résultats', [
      "Les résultats de la Société sont affectés conformément à la décision de l'assemblée générale ordinaire, notamment distribution de dividendes, mise en réserve ou report à nouveau.",
    ].join('\n')),
    article(23, 'Dissolution', [
      "La Société prend fin par l'arrivée du terme fixé, ou par dissolution anticipée décidée par une assemblée générale extraordinaire des Associés dans les conditions de quorum et majorité prévues par les présents Statuts et par la Loi.",
    ].join('\n')),
    article(24, 'Liquidation', [
      "En cas de dissolution, l'Assemblée Générale désigne un ou plusieurs liquidateurs, associés ou tiers, qui seront investis des pouvoirs les plus étendus pour réaliser l'actif et acquitter le passif.",
    ].join('\n')),
    legalTitle('TITRE VII – RÈGLEMENT DES LITIGES'),
    article(25, 'Médiation préalable obligatoire', [
      "Tout différend relatif à l'interprétation ou à l'exécution des présents statuts devra, préalablement à toute action judiciaire, faire l'objet d'une tentative de médiation.",
      'Les associés s\'engagent à désigner un médiateur d\'un commun accord ou, à défaut, à solliciter sa désignation par le Président du Tribunal de commerce du siège social.',
      'La médiation suspend les délais de prescription.',
    ].join('\n')),
    article(26, 'Litiges', [
      'Tout litige relatif aux présents statuts ou à la Société sera soumis au Tribunal compétent du siège social.',
    ].join('\n')),
    legalTitle('TITRE VIII – DISPOSITIONS DIVERSES'),
    article(27, 'Dispositions diverses', [
      'Les associés conviennent que les dispositions suivantes s\'appliquent :',
      '',
      '27.1 - Langue officielle des documents juridiques :',
      "Conformément à l'article 2 de la Constitution française, la langue officielle des statuts et de tous les documents juridiques de la Société, tels que les procès-verbaux, registres et correspondances, est le français. En cas de traduction, seule la version française fait foi.",
      '',
      '27.2 - Droit applicable et Tribunal compétent :',
      'Les statuts sont soumis au droit français.',
      'En cas de litige, compétence exclusive est attribuée au Tribunal compétent du siège social.',
      '',
      '27.3 - Frais de constitution avancés par les associés :',
      'Tous les frais, droits et honoraires engagés pour la constitution de la Société sont avancés par les associés agissant au nom et pour le compte de la Société en formation. Le détail de ces frais figure en annexe aux présents statuts.',
      '',
      'Ces sommes donnent lieu à ouverture d\'un compte courant d\'associé au bénéfice des associés ayant supporté ces dépenses.',
      '',
      "La Société rembourse ces avances dans un délai raisonnable à compter de son immatriculation au Registre du Commerce et des Sociétés, sous réserve de justification des dépenses.",
      '',
      '27.4 - Disposition transitoire :',
      "La Société accepte l'usage de la signature électronique pour les convocations, consultations écrites et signatures de procès-verbaux, dans les conditions prévues par la loi.",
    ].join('\n')),
  ];

  return {
    cover: buildWilliamCover({
      ...data,
      legalFormLabel: 'Société par Actions Simplifiée (SAS)',
      legalFormShort: 'Société par Actions Simplifiée',
    }),
    blocks,
    annexes: buildStandardAnnexes(data),
    signatures: buildWilliamSignatures(data),
    footerNotice: '',
    metadata: { legalForm: 'SAS', template: 'william_establishments_sas_reference', ...data.metadataBundle },
  };
};
