-- Verrouillage Supabase PostgREST : activer RLS sur toutes les tables applicatives.
-- L'API Greffio passe par le backend (service role / DATABASE_URL direct).
-- Sans RLS, la clé anon Supabase expose toutes les données publiquement.

ALTER TABLE IF EXISTS users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS refresh_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS password_reset_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS dossiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS dossier_status_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payment_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS generated_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS document_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS email_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ops_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mfa_recovery_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS credential_unlock_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS push_device_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mfa_trusted_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS resource_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS signature_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS schema_migrations ENABLE ROW LEVEL SECURITY;

-- Révoquer l'accès direct anon/authenticated (PostgREST) sur le schéma public.
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
